### ISSUE TITLE
Usage in TYPO3 6.2 works fine

### ISSUE THREAD

**Issue by christophlehmann** [Kephson/news_falttnewsimport#1]
After removing the dependencies the migration works fine with

* TYPO3 6.2
* news 3.2.8
* tt_news 3.6.0

We only migrated the tx_falttnews_fal_images field since there were no tt_news with tx_falttnews_fal_media

**Comment by Kephson** [comment]
Thanks for the feedback, I updated now the dependencies and released a new version.
