### ISSUE TITLE
Support command line execution

### ISSUE THREAD

**Issue by jokumer** [Kephson/news_falttnewsimport#2]
Hey Ephraim,

Thanks for your working solution to migrate FAL entries of EXT:tt_news to EXT:news.
I missed a way to execute this migration via command line and did therefor implement your code as an option in EXT:news_ttnewsimport, including additional improvements.

https://github.com/ext-news/news_ttnewsimport/pull/53/commits/4ef8aa5f494cfbb5dec3f7a1129c59cc745905cb#diff-a512177f57e6855e06e2aac44ff82307

**Comment by Kephson** [comment]
Thanks for this, I will review that and update the extension.

**Comment by Kephson** [comment]
Closing this, because I don't want to extend the plugin at the moment. If possible please add a pull request and I will merge it.
